# -*- coding: utf-8 -*-
"""The Collatz Sequence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16vtztzn-5hDhxDGFO1LJpQNVAl4zKNDG
"""

def collatz(number):

  while number != 1:
    if number % 2 == 0:
      number = number // 2
    else:
      number = (3 * number) + 1

    print(number, end = ' ')

try:
  number = int(input('enter a number: '))
  collatz(number)

except ValueError:
  print('Please enter a valid number!')